import { createSlice } from '@reduxjs/toolkit';

// 1. Define the Initial State
// This represents the default structure of our auth data before any actions are dispatched.
const initialState = {
  isAuthenticated: false, // Tracks if a user is logged in
  user: null,            // Stores user profile info (e.g. name, email)
  isLoading: false,      // Tracks active asynchronous login requests (spinning state)
  error: null,           // Stores any authentication error message
};

// 2. Create the Slice
// A Redux Slice is a collection of Redux reducer logic and actions for a single feature.
// Under the hood, createSlice uses Immer to allow us to write "mutating" updates safely.
const authSlice = createSlice({
  name: 'auth', // Namespace for action types generated by this slice
  initialState,
  reducers: {
    // Action: Start the login process
    loginStart: (state) => {
      state.isLoading = true;
      state.error = null;
    },
    // Action: Successful login
    loginSuccess: (state, action) => {
      state.isLoading = false;
      state.isAuthenticated = true;
      state.user = action.payload; // Store the user data sent via action dispatch
      state.error = null;
    },
    // Action: Failed login
    loginFailure: (state, action) => {
      state.isLoading = false;
      state.isAuthenticated = false;
      state.user = null;
      state.error = action.payload; // Store error message passed in the action
    },
    // Action: Logout
    logout: (state) => {
      state.isLoading = false;
      state.isAuthenticated = false;
      state.user = null;
      state.error = null;
    },
  },
});

// 3. Export Action Creators
// Redux Toolkit automatically generates action creators (functions that return { type, payload })
// for each of our reducer functions. We can import these and dispatch them in our React components.
export const { loginStart, loginSuccess, loginFailure, logout } = authSlice.actions;

// 4. Simulated Async Login Thunk
// In a real application, you would make an API request to verify user credentials.
// This thunk simulates an async API call with a 1.5-second timeout delay.
export const performLoginAsync = (email, password) => {
  return async (dispatch) => {
    // Step A: Trigger loading state so UI can show a loading indicator
    dispatch(loginStart());

    try {
      // Simulate network request latency (1.5 seconds)
      await new Promise((resolve) => setTimeout(resolve, 1500));

      // Simple credential check validation
      if (email.trim().toLowerCase() === 'user@example.com' && password === 'password123') {
        const dummyUser = {
          name: 'Jane Doe',
          email: email.trim().toLowerCase(),
          role: 'Premium User',
          joinedDate: 'August 2026',
        };
        // Step B: Dispatch success with payload
        dispatch(loginSuccess(dummyUser));
      } else {
        // Step C: Dispatch failure with custom error message
        dispatch(loginFailure('Invalid credentials. Use user@example.com and password123.'));
      }
    } catch (err) {
      dispatch(loginFailure(err.message || 'An unexpected error occurred.'));
    }
  };
};

// 5. Export Reducer
// The root store needs to combine this reducer to configure the global state.
export default authSlice.reducer;
